### ISSUE TITLE
Can not understand how to use ethconsole.

### ISSUE THREAD

**Issue by sanyinchen** [ethereum/ethereum-console#20]
As the title ,I can't understand how to use ethconsole.When I installed cpp-ethereum and run ethconsole.It's tell me 'Could not connect to node. Please start an Ethereum node first.'

`root@vultr:~/sources/downloads# ethconsole
Connecting to node at /root/.ethereum/geth.ipc
IPC Connection Error { Error: connect ENOENT /root/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/root/.ethereum/geth.ipc' }
Could not connect to node. Please start an Ethereum node first.`

It's doubt me.Please tell me how to do that.Thanks,best wishes!

**Comment by sanyinchen** [comment]
`Connecting to node at /root/.ethereum/geth.ipc  
IPC Connection Error { Error: connect ENOENT /root/.ethereum/geth.ipc  
    at Object.exports._errnoException (util.js:1026:11)  
    at exports._exceptionWithHostPort (util.js:1049:20)  
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)  
  code: 'ENOENT',  
  errno: 'ENOENT',  
  syscall: 'connect',  
  address: '/root/.ethereum/geth.ipc' }  
Could not connect to node. Please start an Ethereum node first.
`

**Comment by sanyinchen** [comment]
Connecting to node at /root/.ethereum/geth.ipc  
IPC Connection Error { Error: connect ENOENT /root/.ethereum/geth.ipc  
    at Object.exports._errnoException (util.js:1026:11)  
    at exports._exceptionWithHostPort (util.js:1049:20)  
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)  
  code: 'ENOENT',  
  errno: 'ENOENT',  
  syscall: 'connect',  
  address: '/root/.ethereum/geth.ipc' }  
Could not connect to node. Please start an Ethereum node first.

**Comment by vedk** [comment]
Perhaps you need to run cpp-ethereum, _i.e._ `eth` first.
If you are running GNU/Linux, run the following in a terminal:

`$ eth`

Then open a new terminal and run ethconsole:

`$ ethconsole`

It should work now.

**Comment by Altaimorin** [comment]
What is I'm running on Windows?
